In [1]:
import numpy as np

In [2]:
arr1 =np.array([4,5,6])
print(arr1)

[4 5 6]


In [3]:
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
print(arr1.shape)

(3,)


In [5]:
print(arr1[2])

6


In [6]:
arr1[1]=9

In [7]:
arr1

array([4, 9, 6])

In [9]:
arr2=np.array([[4,5,6],[1,2,3]])
arr2

array([[4, 5, 6],
       [1, 2, 3]])

In [10]:
arr2[1,2]

np.int64(3)

In [11]:
arr2[1,1]

np.int64(2)

In [12]:
print(arr2.shape)

(2, 3)


In [13]:
arr2[1][-2]

np.int64(2)

In [14]:
arrC=np.array(['Ravi', 'Kiran', 'Ediga', 'Gowd','Rude'])
arrC

array(['Ravi', 'Kiran', 'Ediga', 'Gowd', 'Rude'], dtype='<U5')

In [18]:
arrM =np.arange(0,30,3)
arrM

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [19]:
arrL = np.linspace(0,15,23)
arrL


array([ 0.        ,  0.68181818,  1.36363636,  2.04545455,  2.72727273,
        3.40909091,  4.09090909,  4.77272727,  5.45454545,  6.13636364,
        6.81818182,  7.5       ,  8.18181818,  8.86363636,  9.54545455,
       10.22727273, 10.90909091, 11.59090909, 12.27272727, 12.95454545,
       13.63636364, 14.31818182, 15.        ])

In [20]:
arr =np.random.rand(8)

In [21]:
arr

array([0.82309061, 0.22151249, 0.46374255, 0.71936954, 0.53873223,
       0.67874215, 0.76908179, 0.44684894])

In [25]:
print(np.zeros(8))
print('/n')
print(np.zeros((3,4)))

[0. 0. 0. 0. 0. 0. 0. 0.]
/n
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
print(np.ones((4,2,4)))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [28]:
arr =[0,1,2,'R']
print(np.repeat(arr,4))

['0' '0' '0' '0' '1' '1' '1' '1' '2' '2' '2' '2' 'R' 'R' 'R' 'R']


In [31]:
arr4=np.random.rand(6,6)
arr4

array([[0.38194161, 0.44970616, 0.99471252, 0.08917653, 0.77679356,
        0.97321982],
       [0.82750477, 0.78635422, 0.57306015, 0.46459353, 0.53182412,
        0.49342586],
       [0.07207207, 0.95084781, 0.33226798, 0.31468618, 0.45523635,
        0.60993206],
       [0.34144897, 0.85046344, 0.74654994, 0.19233904, 0.00342804,
        0.22163206],
       [0.72675292, 0.63147937, 0.15470964, 0.30711778, 0.17066398,
        0.08092807],
       [0.71477535, 0.93080806, 0.56127548, 0.07555964, 0.96192713,
        0.44366345]])

In [32]:
np.diag(arr4)

array([0.38194161, 0.78635422, 0.33226798, 0.19233904, 0.17066398,
       0.44366345])

In [34]:
arr4.ndim

2

In [36]:
arr4.size



36

In [40]:
np.random.randint(-5,30,7)

array([ 1,  5,  0, 15, 10,  9, -3], dtype=int32)

In [41]:
arr4/2

array([[0.19097081, 0.22485308, 0.49735626, 0.04458826, 0.38839678,
        0.48660991],
       [0.41375238, 0.39317711, 0.28653008, 0.23229677, 0.26591206,
        0.24671293],
       [0.03603603, 0.47542391, 0.16613399, 0.15734309, 0.22761818,
        0.30496603],
       [0.17072449, 0.42523172, 0.37327497, 0.09616952, 0.00171402,
        0.11081603],
       [0.36337646, 0.31573968, 0.07735482, 0.15355889, 0.08533199,
        0.04046403],
       [0.35738768, 0.46540403, 0.28063774, 0.03777982, 0.48096357,
        0.22183173]])

In [42]:
np.exp(arr4)

array([[1.46512654, 1.56785142, 2.70394691, 1.09327363, 2.1744887 ,
        2.64645184],
       [2.28760352, 2.19537794, 1.7736865 , 1.59136722, 1.7020342 ,
        1.6379179 ],
       [1.0747328 , 2.58790279, 1.3941264 , 1.36982937, 1.57654596,
        1.84030636],
       [1.4069848 , 2.34073139, 2.10970883, 1.21208139, 1.00343393,
        1.24811206],
       [2.06835358, 1.88039031, 1.16731896, 1.35950108, 1.18609213,
        1.0842929 ],
       [2.04372752, 2.53655804, 1.75290688, 1.07848754, 2.61673441,
        1.55840592]])

In [43]:
arr4


array([[0.38194161, 0.44970616, 0.99471252, 0.08917653, 0.77679356,
        0.97321982],
       [0.82750477, 0.78635422, 0.57306015, 0.46459353, 0.53182412,
        0.49342586],
       [0.07207207, 0.95084781, 0.33226798, 0.31468618, 0.45523635,
        0.60993206],
       [0.34144897, 0.85046344, 0.74654994, 0.19233904, 0.00342804,
        0.22163206],
       [0.72675292, 0.63147937, 0.15470964, 0.30711778, 0.17066398,
        0.08092807],
       [0.71477535, 0.93080806, 0.56127548, 0.07555964, 0.96192713,
        0.44366345]])

In [45]:
np.log2(arr4)

array([[-1.38857599e+00, -1.15294546e+00, -7.64845416e-03,
        -3.48719216e+00, -3.64396862e-01, -3.91623993e-02],
       [-2.73160467e-01, -3.46748770e-01, -8.03241517e-01,
        -1.10595902e+00, -9.10978878e-01, -1.01909477e+00],
       [-3.79441592e+00, -7.27136429e-02, -1.58958082e+00,
        -1.66801426e+00, -1.13531232e+00, -7.13279555e-01],
       [-1.55025810e+00, -2.33678875e-01, -4.21689317e-01,
        -2.37827647e+00, -8.18839911e+00, -2.17376153e+00],
       [-4.60463133e-01, -6.63192498e-01, -2.69236503e+00,
        -1.70313605e+00, -2.55076949e+00, -3.62721603e+00],
       [-4.84438205e-01, -1.03444391e-01, -8.33219052e-01,
        -3.72624043e+00, -5.60004838e-02, -1.17246238e+00]])

In [48]:
np.tan(arr4)

array([[0.40166583, 0.48269271, 1.53944314, 0.08941367, 0.98293718,
        1.46932439],
       [1.0879693 , 1.00191393, 0.64529444, 0.50118296, 0.58836998,
        0.53779675],
       [0.07219712, 1.40089126, 0.34506091, 0.32550234, 0.48952972,
        0.69881773],
       [0.355368  , 1.13939724, 0.92517282, 0.19474649, 0.00342806,
        0.22533372],
       [0.88908686, 0.73138299, 0.1559559 , 0.31715247, 0.17234045,
        0.08110521],
       [0.86786629, 1.34313719, 0.62872779, 0.07570376, 1.43423255,
        0.47526368]])

In [50]:
np.sum(arr4, axis=0)

array([3.0644957 , 4.59965906, 3.36257572, 1.4434727 , 2.89987319,
       2.82280131])

In [52]:
np.max(arr4)

np.float64(0.9947125237350094)

In [54]:
np.mean(arr4)

np.float64(0.5053577130865852)

In [55]:
np.median(arr4)

np.float64(0.4790096962666672)

In [56]:
np.std(arr4)

np.float64(0.2961901712210195)

In [57]:
np.var(arr4)

np.float64(0.08772861752793683)

In [60]:
arr4[1:2:-1]

array([], shape=(0, 6), dtype=float64)

In [62]:
np.sort(arr4,axis=0)

array([[0.07207207, 0.44970616, 0.15470964, 0.07555964, 0.00342804,
        0.08092807],
       [0.34144897, 0.63147937, 0.33226798, 0.08917653, 0.17066398,
        0.22163206],
       [0.38194161, 0.78635422, 0.56127548, 0.19233904, 0.45523635,
        0.44366345],
       [0.71477535, 0.85046344, 0.57306015, 0.30711778, 0.53182412,
        0.49342586],
       [0.72675292, 0.93080806, 0.74654994, 0.31468618, 0.77679356,
        0.60993206],
       [0.82750477, 0.95084781, 0.99471252, 0.46459353, 0.96192713,
        0.97321982]])

In [63]:
arr4.T

array([[0.38194161, 0.82750477, 0.07207207, 0.34144897, 0.72675292,
        0.71477535],
       [0.44970616, 0.78635422, 0.95084781, 0.85046344, 0.63147937,
        0.93080806],
       [0.99471252, 0.57306015, 0.33226798, 0.74654994, 0.15470964,
        0.56127548],
       [0.08917653, 0.46459353, 0.31468618, 0.19233904, 0.30711778,
        0.07555964],
       [0.77679356, 0.53182412, 0.45523635, 0.00342804, 0.17066398,
        0.96192713],
       [0.97321982, 0.49342586, 0.60993206, 0.22163206, 0.08092807,
        0.44366345]])

In [66]:
arr4[:2,:].T

array([[0.38194161, 0.82750477],
       [0.44970616, 0.78635422],
       [0.99471252, 0.57306015],
       [0.08917653, 0.46459353],
       [0.77679356, 0.53182412],
       [0.97321982, 0.49342586]])

In [68]:
arr4[:2,:].transpose()

array([[0.38194161, 0.82750477],
       [0.44970616, 0.78635422],
       [0.99471252, 0.57306015],
       [0.08917653, 0.46459353],
       [0.77679356, 0.53182412],
       [0.97321982, 0.49342586]])

In [69]:
arr4[:2,:].flatten()

array([0.38194161, 0.44970616, 0.99471252, 0.08917653, 0.77679356,
       0.97321982, 0.82750477, 0.78635422, 0.57306015, 0.46459353,
       0.53182412, 0.49342586])

In [70]:
arr4 =np.array([5,6,7,8,9])

In [71]:
arr4

array([5, 6, 7, 8, 9])

In [72]:
arr5=np.append(arr,7)
arr4

array([5, 6, 7, 8, 9])

In [73]:
arr5=np.insert(arr4,0,[1,2,3])
arr5

array([1, 2, 3, 5, 6, 7, 8, 9])

In [75]:
arr6=np.delete(arr5,[2,5])
arr6

array([1, 2, 5, 6, 8, 9])

In [77]:
arrR=arr6.copy()
arrR

array([1, 2, 5, 6, 8, 9])

In [78]:
arr5=np.array([[1,2,3,4],[5,6,7,8]])
arr6=np.array([[5,6,7,8],[1,2,3,4]])
arr_cat=np.concatenate((arr5,arr6),axis=0)
print(arr_cat)

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]


In [79]:
ctV=np.vstack((arr1,arr2))
ctV

array([[4, 9, 6],
       [4, 5, 6],
       [1, 2, 3]])

In [81]:
ct=np.hstack((arr5,arr6))
ct

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [5, 6, 7, 8, 1, 2, 3, 4]])

In [82]:
arrE =np.array([1,2,3,4,5,6,7,1,2,3,4])
np.unique(arrE)

array([1, 2, 3, 4, 5, 6, 7])

In [83]:
uniques,counts =np.unique(arrE,return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6 7]
[2 2 2 2 1 1 1]


In [87]:
#INTERSECTION ,DIFFERNTITION ,NEITHER
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])

print(np.intersect1d(arr1,arr2))
print(np.union1d(arr1,arr2))
print(np.setdiff1d(arr1,arr2))
print(np.setxor1d(arr1,arr2))

[3 4]
[1 2 3 4 5 6]
[1 2]
[1 2 5 6]


# 